#
# SPEC originally generated by:
#  ./hack/gofed.sh repo2spec  --detect github.com/xtaci/kcptun -f --with-build
#
# see
#  https://github.com/gofed/gofed
# for more details
#


%global debug_package %{nil}

%if ! 0%{?goget:1}
%define goget(o:) go get %{?**};
%endif

%if ! 0%{?gobuild:1}
%define gobuild(o:) go build -ldflags "${LDFLAGS:-} -B 0x$(head -c20 /dev/urandom|od -An -tx1|tr -d ' \\n')" -a -v -x %{?**};
%endif

%global provider        github
%global provider_tld    com
%global project         xtaci
%global repo            kcptun
# https://github.com/xtaci/kcptun
%global provider_prefix %{provider}.%{provider_tld}/%{project}/%{repo}
%global import_path     %{provider_prefix}
%global commit          bf1d0d641903370e57ab8fc036295a6ef0cabce0
%global shortcommit     %(c=%{commit}; echo ${c:0:7})
%global date_ver        20180305

Name:           golang-%{provider}-%{project}-%{repo}
Version:        0
Release:        0.1.git%{shortcommit}%{?dist}
Summary:        A Fast & Secure Tunnel Based On KCP with N:M Multiplexing.
License:        MIT
URL:            https://%{provider_prefix}
# https://%{provider_prefix}/archive/v%{date_ver}.tar.gz
Source0:        %{repo}-%{date_ver}.tar.gz
Source1:        kcptun.conf
Source2:        kcptun-client@.service
Source3:        kcptun-server@.service

# e.g. el6 has ppc64 arch without gcc-go, so EA tag is required
ExclusiveArch:  %{?go_arches:%{go_arches}}%{!?go_arches:%{ix86} x86_64 aarch64 %{arm}}
# If go_compiler is not set to 1, there is no virtual provide. Use golang instead.
BuildRequires:  %{?go_compiler:compiler(go-compiler)}%{!?go_compiler:golang}

%description
%{summary}

%prep
%setup -q -n %{repo}-%{date_ver}

export GOPATH=$(pwd):%{gopath}

%goget %{import_path}/client
%goget %{import_path}/server

%build
mkdir -p src/%{provider}.%{provider_tld}/%{project}

export GOPATH=$(pwd):%{gopath}

%gobuild -o bin/kcptun-client %{import_path}/client
%gobuild -o bin/kcptun-server %{import_path}/server

%install
install -d -p %{buildroot}%{_bindir}
install -p -m 0755 bin/kcptun-client %{buildroot}%{_bindir}
install -p -m 0755 bin/kcptun-server %{buildroot}%{_bindir}

install -d -p %{buildroot}%{_sysconfdir}/kcptun
install -m 0644 %{SOURCE1} %{buildroot}%{_sysconfdir}/kcptun

%if 0%{?rhel} >= 7
install -d -p -p %{buildroot}%{_unitdir}
install -m 0644 %{SOURCE2} %{SOURCE3} %{buildroot}%{_unitdir}/
%endif

#define license tag if not already defined
%{!?_licensedir:%global license %doc}

%files
%license LICENSE.md
%doc README.md
%{_bindir}/kcptun-client
%{_bindir}/kcptun-server

%config(noreplace) %{_sysconfdir}/kcptun/kcptun.conf

%if 0%{?rhel} >= 7
%{_unitdir}/kcptun-client@.service
%{_unitdir}/kcptun-server@.service
%endif

%changelog
